Added Hibernate and FlyWay. Updated main entities.
RomanSulymka/spring-mentee-project pull request #2
Opened 2023-04-06 10:57 UTC by RomanSulymka

2023-04-06 13:11 UTC, pdaniv-solo commented on src/main/java/com/sombra/edu/springmenteeproject/repository/BalanceRepository.java
> +                                              @Param("quantity") Double quantity);
Use BigDecimal instead of Double

2023-04-06 13:11 UTC, pdaniv-solo commented on src/main/java/com/sombra/edu/springmenteeproject/repository/BalanceRepository.java
> +                                            @Param("quantity") Double quantity);
Use BigDecimal instead of Double

2023-04-06 13:14 UTC, pdaniv-solo commented on src/main/java/com/sombra/edu/springmenteeproject/service/impl/TransferServiceImpl.java
> +            return getTransfer(transferRequest, Status.FAILED);
If validation doesn't pass throw an error instead of returning failed transfer

2023-04-06 13:15 UTC, pdaniv-solo commented on src/main/java/com/sombra/edu/springmenteeproject/service/impl/WalletServiceImpl.java
>      }
You can use `@RequiredArgsConstructor` instead of creating your own

2023-04-06 13:17 UTC, pdaniv-solo commented on src/main/java/com/sombra/edu/springmenteeproject/service/impl/WalletServiceImpl.java
> +            throw new IllegalArgumentException("Element is already exist");
Create custom `ConflictException` with `409` status code

2023-04-06 13:18 UTC, pdaniv-solo commented on src/main/java/com/sombra/edu/springmenteeproject/service/impl/WalletServiceImpl.java
> +            throw new IllegalArgumentException("Can't find the element");
Why change from `NotFoundException` to `IllegalArgumentException`? the first approach was correct

2023-04-06 13:18 UTC, pdaniv-solo commented on src/main/resources/application.properties
> +spring.flyway.locations=db/migration
Add missing trailing line

2023-04-06 13:19 UTC, pdaniv-solo commented on src/main/java/com/sombra/edu/springmenteeproject/service/impl/WalletServiceImpl.java
> +        log.warn("Element deleted");
Use `info` level, and add id of deleted wallet

2023-04-06 13:21 UTC, pdaniv-solo commented on src/main/java/com/sombra/edu/springmenteeproject/entity/Money.java
> +import jakarta.persistence.*;
Use individual imports instead of wildcard (`*`)

2023-04-06 13:25 UTC, pdaniv-solo commented on src/main/java/com/sombra/edu/springmenteeproject/service/BalanceService.java
> +    Double findBalanceByUserAccountIdAndWalletId(Long userId, Long walletId);
You can simplify the method name with `findUserBalance`, the parameters are describing by what you searching/getting it :) 
Also, better use `get` instead of `find` as we expect it always to be, otherwise throw exception

2023-04-06 19:32 UTC, pdaniv-solo commented on src/main/java/com/sombra/edu/springmenteeproject/entity/Status.java
> +}
It's always a good practice to put empty line at the end of file

2023-04-13 11:21 UTC, pauldaniv approved these changes

2023-04-18 17:45 UTC, pauldaniv commented on src/main/java/com/sombra/edu/springmenteeproject/entity/TransferRequest.java
> +import lombok.*;
Nit pick: avoid using wildcards

2023-04-18 17:49 UTC, pauldaniv commented on src/main/java/com/sombra/edu/springmenteeproject/service/impl/TransferServiceImpl.java
> +            return false;
Instead of returning false when validation does not pass simply throw an exception with details of what went wrong

2023-04-18 17:50 UTC, pauldaniv commented on src/main/java/com/sombra/edu/springmenteeproject/service/impl/TransferServiceImpl.java
> +        transferRequestService.saveTransferRequest(transferRequest);
Why does `get` method performs `save` operations?
Ether move the save logic outside of it or rename the method accordingly

2023-04-18 17:51 UTC, pauldaniv commented on src/main/java/com/sombra/edu/springmenteeproject/service/impl/UserAccountServiceImpl.java
> +        return userAccountRepository.findById(userId).orElseThrow();
Throw not found exception instead of generic one

2023-04-18 17:55 UTC, pauldaniv commented on src/main/resources/db/migration/initial_data.sql
Put a version tag in this file name too

2023-04-18 17:55 UTC, pauldaniv requested changes
Added few comments

2023-04-26 10:12 UTC, pauldaniv approved these changes
LGTM

2023-04-26 18:27 UTC, merged